--- #Master Playbook for AppServices
- hosts: controller
  user: test
  pre_tasks:
    - name: Checks Ansible System
      setup: filter=ansible_system
      register: system_type
    - debug: var=system_type
  roles:
    - { role: linux_testsvcValidate, when: "ansible_system == 'Linux'" }
