--- #Master Playbook for AppServices
- hosts: controller
  user: test
  pre_tasks:
    - name: Checks Ansible System
      setup: filter=ansible_system
      register: system_type
    - debug: msg="System Type of this machine is {{ system_type }}
  roles:
    - { role: linux_testsvc, when: "ansible_system == 'Linux'" }